[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['@openzeppelin=lib/openzeppelin-contracts/']
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config