[profile.default]
src = 'contracts'
test='test'
script='scripts/foundry'
out = 'out'
libs = ['node_modules', 'lib']
cache_path  = 'cache_forge'
remappings = ['forge-std=lib/forge-std/src', '@openzeppelin=lib/openzeppelin-contracts', '@uniswap/v3-periphery=lib/v3-periphery', '@uniswap/v3-core=lib/v3-core']
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config