[profile.default]
src = 'contracts'
test='test-foundry'
script='scripts-foundry'
out = 'out'
libs = ['lib']
remappings = ['forge-std=lib/forge-std/src', '@openzeppelin=lib/openzeppelin-contracts', '@uniswap/v3-periphery=lib/v3-periphery', '@uniswap/v3-core=lib/v3-core']
optimizer = true
optimizer_runs = 20_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config